pollApp/pollApp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pollApp/', include('webapp.urls'))
]

pollApp/webapp/urls.py
from django.urls import path, include
from . import views

app_name='pollApp'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:question_id>', views.details, name='detail'),
    path('<int:question_id>/result/', views.result, name='result'),
    path('<int:question_id>/vote/', views.vote, name='vote')
]

pollApp/webapp/models.py
from django.db import models

# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    
    def __str__(self):
        return self.choice_text

pollApp/webapp/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .models import Question, Choice
from django.urls import reverse

# Create your views here.
def index(req):
    ques = Question.objects.all()
    # print(ques)
    return render(req, 'index.html', {'questions':ques})

def details(req, question_id):
    ques = Question.objects.get(pk=question_id)
    return render(req, 'details.html', {'question':ques})

def result(req, question_id):
    ques = Question.objects.get(pk=question_id)
    return render(req, 'result.html', {'question':ques})

def vote(req, question_id):
    ques = Question.objects.get(pk=question_id)
    errorMessage = 'Please Select one choice'
    try:
        selected_choice = ques.choice_set.get(pk = req.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        print("Exception Occurred...")
        # return render(req, 'details.html', {
        #     'ques' : ques,
        #     'errorMessage' : 'Please Select one choice'
        # })
        return HttpResponseRedirect(reverse('pollApp:detail', args=(question_id,)))
    else:
        selected_choice.votes += 1
        selected_choice.save()

        # return render(req, 'result.html', {'question': ques})
        return HttpResponseRedirect(reverse('pollApp:result', args=(question_id,)))

pollApp/webapp/templates/base.html
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>Hello, world!</title>
    <style>
        h1 {
            margin: 20px 0px;
            padding-bottom: 20px;
            text-align: center;
            border-bottom: 1px solid red;
        }
        
        .product {
            margin-bottom: 20px;
        }
        
        .product .card {
            padding-top: 10px;
        }
    </style>
</head>

<body>

    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        <a class="navbar-brand" href="#">Navbar</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                  <span class="navbar-toggler-icon"></span>
                </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'pollApp:index' %}">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Products</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Electronics
                      </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="#">Mobile</a>
                        <a class="dropdown-item" href="#">Tabs</a>
                        <a class="dropdown-item" href="#">Something else here</a>
                    </div>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#" tabindex="-1" aria-disabled="true">Contact</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#" tabindex="-1" aria-disabled="true">About</a>
                </li>
            </ul>
        </div>
    </nav>

    <div id="content">
        <div class="container">
            {% block content %} {% endblock %}
        </div>
    </div>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>

</html>

pollApp/webapp/templates/details.html
{% extends 'base.html' %} {% block content %}

<h1>{{question}}</h1>

<form action="{% url 'pollApp:vote' question.id %}" method="post"> {% csrf_token %}
    <ul class="list-group">
        {% for choice in question.choice_set.all %}
        <li class="list-group-item">
            <input type="radio" required name="choice" id="{{forloop.counter}}" value="{{choice.id}}">
            <label for="{{forloop.counter}}">{{choice.choice_text}}</label>
        </li>
        {% endfor %}
    </ul>
    <br>
    <input class="btn btn-primary w-25" type="submit" value="Vote">
</form>


{% endblock %}

pollApp/webapp/templates/index.html
{% extends 'base.html' %} {% block content %}

<h1>Welcome to Poll App</h1>

<!-- <h2>{{questions}}</h2> -->
<h2>Questions</h2>
<ul>
    {% for ques in questions %}
    <li>
        <a href="{% url 'pollApp:detail' ques.id %}">
            {{ques.question_text}}
        </a>
        <span>
            {{ques.pub_date}}
        </span>
    </li>
    {% endfor %}
</ul>

{% endblock %}

pollApp/webapp/templates/result.html
{% extends 'base.html' %} {% block content %}

<h1>Results</h1>

<h2>Question is : {{question.question_text}}</h2>

<div id="result">
    <ul class="list-group">
        {% for choice in question.choice_set.all %}
        <li class="list-group-item">
            {{choice.choice_text}} => {{choice.votes}}
        </li>
        {% endfor %}
    </ul>
</div>

<a href="{% url 'pollApp:detail' question.id %}">Vote Again</a> {% endblock %}